title: MH Tutorials Cleanup Stuff

# theme: jekyll-theme-architect
# remote_theme: jekyll/minima
theme: jekyll-theme-architect

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 10
paginate_path: posts/page:num/

url: "https://mh-github.github.io"